IF DB_ID('MaintenanceTicketsDb') IS NULL
    CREATE DATABASE MaintenanceTicketsDb;
GO
USE MaintenanceTicketsDb;
GO

IF OBJECT_ID('dbo.TicketHistory', 'U') IS NOT NULL DROP TABLE dbo.TicketHistory;
IF OBJECT_ID('dbo.Tickets', 'U') IS NOT NULL DROP TABLE dbo.Tickets;
GO

CREATE TABLE dbo.Tickets (
    Id INT IDENTITY(1000,1) PRIMARY KEY,
    Title NVARCHAR(150) NOT NULL,
    AssetCode VARCHAR(30) NOT NULL,
    Description NVARCHAR(2000) NULL,
    Priority VARCHAR(10) NOT NULL,
    Status VARCHAR(20) NOT NULL CONSTRAINT DF_Tickets_Status DEFAULT 'PENDING',
    Diagnosis NVARCHAR(2000) NULL,
    Resolution NVARCHAR(2000) NULL,
    ReportedBy NVARCHAR(100) NOT NULL,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Tickets_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_Tickets_UpdatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT CK_Tickets_Priority CHECK (Priority IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    CONSTRAINT CK_Tickets_Status CHECK (Status IN ('PENDING','IN_PROGRESS','RESOLVED'))
);
GO

CREATE TABLE dbo.TicketHistory (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    TicketId INT NOT NULL,
    EventType VARCHAR(30) NOT NULL,
    FromStatus VARCHAR(20) NULL,
    ToStatus VARCHAR(20) NULL,
    Comment NVARCHAR(2000) NULL,
    PerformedBy NVARCHAR(100) NOT NULL,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_TicketHistory_CreatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_TicketHistory_Tickets FOREIGN KEY (TicketId) REFERENCES dbo.Tickets(Id) ON DELETE NO ACTION
);
GO
